// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lriqkvaxczvecwzvngqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyaXFrdmF4Y3p2ZWN3enZuZ3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyOTc1NjYsImV4cCI6MjA3Mjg3MzU2Nn0.W5zZ3a6zwiAD5pPpEGUyz9uxCT1-LC_1B8BXO3HqPFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);